# Generated by Django 3.2 on 2021-04-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_pages', models.PositiveIntegerField()),
                ('number_of_books', models.PositiveIntegerField()),
                ('date_of_finishing', models.DateTimeField(verbose_name='date of finishing the book')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_storage.author')),
            ],
        ),
    ]
