# Generated by Django 3.2 on 2021-04-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0002_rename_name_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
